export const audioMap = {
  "Welcome to Word Problems Using Subtraction!": "/assets/audio/audio_welcome_to_word_problems_using_subtraction__0.mp3",
  "In this lesson, you will learn how to solve subtraction word problems.": "/assets/audio/audio_in_this_lesson__you_will_learn_how_to_solve_subtra_1.mp3",
  "Let's start our adventure!": "/assets/audio/audio_let_s_start_our_adventure__2.mp3",
  "Siti had 10 balloons at her party. Some flew away! Now she has 6. How many flew away?": "/assets/audio/audio_siti_had_10_balloons_at_her_party__some_flew_away__3.mp3",
  "Hmm... I wonder how we can find out?": "/assets/audio/audio_hmm____i_wonder_how_we_can_find_out__4.mp3",
  "Let's learn how to solve it together!": "/assets/audio/audio_let_s_learn_how_to_solve_it_together__5.mp3",
  "Wei Ming is at the hawker centre. He has 9 fishballs!": "/assets/audio/audio_wei_ming_is_at_the_hawker_centre__he_has_9_fishbal_6.mp3",
  "He eats 4 fishballs. Yum, yum, yum!": "/assets/audio/audio_he_eats_4_fishballs__yum__yum__yum__7.mp3",
  "How many fishballs does Wei Ming have left?": "/assets/audio/audio_how_many_fishballs_does_wei_ming_have_left__8.mp3",
  "What do we know? The whole is 9. One part is 4.": "/assets/audio/audio_what_do_we_know__the_whole_is_9__one_part_is_4__9.mp3",
  "We need to find the other part. This is what is left!": "/assets/audio/audio_we_need_to_find_the_other_part__this_is_what_is_le_10.mp3",
  "Draw the number bond. Put 9 at the top. Put 4 in one circle.": "/assets/audio/audio_draw_the_number_bond__put_9_at_the_top__put_4_in_o_11.mp3",
  "Now write the number sentence. 9 minus 4 equals 5.": "/assets/audio/audio_now_write_the_number_sentence__9_minus_4_equals_5__12.mp3",
  "Wei Ming has 5 fishballs left!": "/assets/audio/audio_wei_ming_has_5_fishballs_left__13.mp3",
  "Station One! Read the story. Now place the counters.": "/assets/audio/audio_station_one__read_the_story__now_place_the_counter_14.mp3",
  "Great! Now take away the right number of counters.": "/assets/audio/audio_great__now_take_away_the_right_number_of_counters__15.mp3",
  "How many are left?": "/assets/audio/audio_how_many_are_left__16.mp3",
  "Station Two! Look at the number bond.": "/assets/audio/audio_station_two__look_at_the_number_bond__17.mp3",
  "Drag the numbers into the correct circles.": "/assets/audio/audio_drag_the_numbers_into_the_correct_circles__18.mp3",
  "The whole goes at the top. The parts go at the bottom.": "/assets/audio/audio_the_whole_goes_at_the_top__the_parts_go_at_the_bot_19.mp3",
  "Station Three! Write the subtraction sentence.": "/assets/audio/audio_station_three__write_the_subtraction_sentence__20.mp3",
  "Tap each box and type the number.": "/assets/audio/audio_tap_each_box_and_type_the_number__21.mp3",
  "Then complete the answer sentence.": "/assets/audio/audio_then_complete_the_answer_sentence__22.mp3",
  "Amazing! You solved the word problem!": "/assets/audio/audio_amazing__you_solved_the_word_problem__23.mp3",
  "Brilliant! You used the number bond perfectly!": "/assets/audio/audio_brilliant__you_used_the_number_bond_perfectly__24.mp3",
  "You're a maths superstar! Keep going!": "/assets/audio/audio_you_re_a_maths_superstar__keep_going__25.mp3",
  "Wonderful! That's exactly right!": "/assets/audio/audio_wonderful__that_s_exactly_right__26.mp3",
  "Let's try again! Read the problem carefully.": "/assets/audio/audio_let_s_try_again__read_the_problem_carefully__27.mp3",
  "Almost there! Think about what we need to find.": "/assets/audio/audio_almost_there__think_about_what_we_need_to_find__28.mp3",
  "Hmm... look at the number bond. It will help you!": "/assets/audio/audio_hmm____look_at_the_number_bond__it_will_help_you__29.mp3",
  "Wonderful! You are a Word Problem Champion!": "/assets/audio/audio_wonderful__you_are_a_word_problem_champion__30.mp3",
  "Tell me one thing you learned today!": "/assets/audio/audio_tell_me_one_thing_you_learned_today__31.mp3",
  "Can you make up your own subtraction word problem?": "/assets/audio/audio_can_you_make_up_your_own_subtraction_word_problem__32.mp3",
  "You earned the Problem Spotter badge! You know how to find the question!": "/assets/audio/audio_you_earned_the_problem_spotter_badge__you_know_how_33.mp3",
  "Model Builder badge unlocked! You can draw number bonds like a pro!": "/assets/audio/audio_model_builder_badge_unlocked__you_can_draw_number__34.mp3",
  "Word Problem Whiz! You are amazing at solving word problems!": "/assets/audio/audio_word_problem_whiz__you_are_amazing_at_solving_word_35.mp3",
  "Perfect Story badge! Ten out of ten! You are a superstar!": "/assets/audio/audio_perfect_story_badge__ten_out_of_ten__you_are_a_sup_36.mp3",
  "Streak Legend! Ten in a row! You are on fire!": "/assets/audio/audio_streak_legend__ten_in_a_row__you_are_on_fire__37.mp3",
  "Full Champion! You finished the whole lesson! You are a Word Problem Champion!": "/assets/audio/audio_full_champion__you_finished_the_whole_lesson__you__38.mp3",
  "Singapore Solver! You explored every world! Amazing work!": "/assets/audio/audio_singapore_solver__you_explored_every_world__amazin_39.mp3",
  "Bond and Story Link badge! You solved it all by yourself! Brilliant!": "/assets/audio/audio_bond_and_story_link_badge__you_solved_it_all_by_yo_40.mp3"
};
